CREATE TABLE IF NOT EXISTS Users(
id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name  VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS Item_Request(
id            BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
requestor_id     BIGINT    NOT NULL CONSTRAINT ItemRequest_users_id_fk REFERENCES Users,
description   VARCHAR   NOT NULL,
created TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS Items(
id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name        VARCHAR(255) NOT NULL,
description VARCHAR      NOT NULL,
available   BOOLEAN      NOT NULL,
owner_id    BIGINT       NOT NULL CONSTRAINT table_name_users_id_fk REFERENCES Users,
request_id  BIGINT       CONSTRAINT items_item_request_id_fk REFERENCES item_request);

CREATE TABLE IF NOT EXISTS Bookings(
id              BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
booker_id       BIGINT    NOT NULL CONSTRAINT Bookings_users_id_fk REFERENCES Users,
item_id         BIGINT    NOT NULL CONSTRAINT Bookings_items_id_fk REFERENCES Items,
start_date_time TIMESTAMP NOT NULL,
end_date_time   TIMESTAMP NOT NULL,
status          VARCHAR   NOT NULL);

CREATE TABLE IF NOT EXISTS Comments(
id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
author_id  BIGINT    NOT NULL CONSTRAINT Comments_users_id_fk REFERENCES Users,
item_id    BIGINT    NOT NULL CONSTRAINT Comments_items_id_fk REFERENCES Items,
text       VARCHAR   NOT NULL,
created    TIMESTAMP NOT NULL);